- README.md
I just enabled coverage support in the WAV package.
> Add WAV.jl to list of packages

- src/Coverage.jl
This supposedly adds a way for `Coverage` to automagically get the git commit information from a repository if it exists, and doesn't hurt anything if it doesn't exist.  I'm having a hard time testing it since I don't think the test submits things to coveralls, but I know at least `Coveralls.query_git_info()` works.
If you want to explicitly disable git information, you call `Coveralls.submit(source_files, git_info_func=nothing)`.  If you have some special way of creating this data, you pass your own callback into `git_info_func`.  Not sure if this is the best API here, but it seems like it should work.
Pinging @timholy for his opinion as well.
> Add ability to query a repository for its git information

- README.md
Simply added QuantileRegression.jl to the list.
> Add QuantileRegression.jl

- .travis.yml
- REQUIRE
- src/Coverage.jl
- src/codecovio.jl
> Add Codecov.io support

- src/codecovio.jl
This is currently working on https://codecov.io/github/kshyatt/julia?ref=master!
> Wrote submit-token function for codecov

- README.md
> Remove coveralls from codecov section

- src/Coverage.jl
- test/runtests.jl
This works now with the newest `Base` master.
> Switched from JuliaParser to Base

- src/Coverage.jl
> Emit helpful warning error instead of BoundsError

- README.md
Thanks for this great package!
Ben
> Add SimJulia to the packages using Coverage

- .travis.yml
- REQUIRE
- src/Coverage.jl
- src/codecovio.jl
- src/coveralls.jl
- src/memalloc.jl
- test/runtests.jl
Fixes deprecations, old and new. (One julia 0.4 depwarn wasn't fixed and now results in an error!)
> Updates for julia 0.5

- test/runtests.jl
or that the package is installed under Pkg.dir
> don't assume julia is on the path

- src/codecovio.jl
- src/coveralls.jl
Addresses https://github.com/JuliaCI/Coverage.jl/pull/144#discussion_r163155810
> Fix conversion of response to string

- README.md
> Add ClimateTools.jl to README, fix #138

- src/codecovio.jl
- src/parser.jl
Checked against julia master, this works.
> Fix parser positioning issue

- README.md
- appveyor.yml
> Enable AppVeyor

- README.md
- src/coveralls.jl
This contains a rebased version of PR #174 by @simonbyrne plus some refactoring.
Closes #174
> Add COVERALLS_TOKEN plus refactoring

- src/coveralls.jl
- test/runtests.jl
Covers most of https://github.com/JuliaCI/Coverage.jl/issues/180, except for the end-to-end test of `submit()` and `submit_local()`.
> Coveralls query_git_info() fix + test + small refactoring

- test/data/testparser.jl.9172.mem
- test/runtests.jl
> Add analyze_malloc test with actual .mem file.

- src/coveralls.jl
- test/runtests.jl
Closes #206.
Tests for local, AppVeyor, Travis and Jenkins. Needed to factor out the construction of the `data` dict into the function `prepare_request()` to allow testing. The other alternative was adding a dry-run kwarg, but that felt less clean.
> Add Coveralls tests.

- test/runtests.jl
I noticed some code was not covered, in particular Jenkins integration, `LCOV.writefile` & `clean_folder`.
> Add tests for various uncovered code paths.

- README.md
> Improve instructions for getting coverage with `Pkg.test`

- README.md
Closes https://github.com/JuliaCI/Coverage.jl/pull/271
> README: Remove AppVeyor badge

- Project.toml
Forgot to bump the version in my previous PR.
> Bump version.
