JuliaCI/Coverage.jl

README.md
REQUIRE
src/Coverage.jl
test/data/testparser.jl
test/runtests.jl

This alters---and perhaps improves---our ability to quantify coverage. It leverages @jakebolewski's JuliaParser.jl to extract the beginning/end line range of "simple" function expressions. It then amends the coverage information by inserting 0 instead of `nothing` for functions that were never compiled.
This is not perfect. Here are deficits that I'm aware of currently:
- It misses functions defined inside a `for f in (:min, :max, ...) @eval begin...` style block (this error will contribute to overly-optimistic estimates of coverage)
- It falsely penalizes `end` statements and the initial `function f(...)` line in a multi-line function (this error will contribute to overly-pessimistic estimates of coverage)
There is also the genuine risk of the line count getting "out of sync", since the …

Improve quality of coverage reports by parsing source files for functions

---

src/Coverage.jl

This is needed now that Base.Cartesian has been greatly slimmed down.

Implement `isfuncexpr` locally. Fixes #48.

---

src/Coverage.jl

And with this fix, we should be able to get actual commit data on [this page](https://coveralls.io/r/JuliaLang/julia).  It turns out that the dict I was passing in is actually a `Dict{ASCIIString,Any}`, NOT a `Dict`, which makes all the difference.  :P

Types are hierarchical, which might, just maybe, be important here

---

README.md

See d4afd1c4cc8904e9bb029e206238e0cec1aec86a in a different code block

Readme: Fix typo in Codecov example (2)

---

src/Coverage.jl
src/codecovio.jl
test/runtests.jl

I've tested this on Coveralls and Codecov. I have a PR I am about to submit to main Julia which will modify things so that each process writes `{filename}.{pid}.cov` instead of `{filename}.cov` as before. I've written some functions to handle the new format. I've checked also that my functions work with the old format and everything seems fine. `merge_coverage_counts` was lifted from CoverageBase - hopefully @timholy is ok with that.

RFC: Modified Coverage to work with .{pid}.cov format

---

src/codecovio.jl

@staticfloat needs this to make the codecov part of the buildbot not die in sadness. Shouldn't affect everyone else's builds... hopefully.

Now you can set the git info in Codecov for buildbots

---

.travis.yml
REQUIRE

Changed `REQUIRE` to ask for pre-release 0.4 and `.travis.yml` to only use `nightly`.

Get set up for julia 0.4!

---

src/parser.jl
test/data/testparser.jl

Fixes #94. Since a `baremodule` is empty checking if you attempt to access the first two arguments of its AST results in a `BoundsError`.

Fix parser bug with baremodule

---

src/codecovio.jl
test/runtests.jl

I am fairly new to Julia so I might have done this all wrong, please don't hesitate to tell me so.  :-)
I ran into a problem with the current Codecov implementation where I could not submit reports to an enterprise installation of Codecov.  The key problem was that the uri needs to point to something like "enterprise-codecov.com" instead of "codecov.io", and even if I am using Travis-CI I need to provide a repo token.
Summary of the proposed changes:
- adding a new generic submission method (i.e. `generic_submit`)
- re-casting existing submission methods in terms of `generic_submit`
- deprecating `submit_token` in favor of a hopefully more intuitive name `submit_local`
- making environment variables consistent with [codecov-bash](https://github.com/codecov/codecov-bash) 
- deprecating …

Generic codecov submissions to support enterprise installations

---

REQUIRE
src/codecovio.jl
src/coveralls.jl

(to whom it may concern...)
https://github.com/JuliaPackaging/Git.jl should be essentially equivalent, but will also ensure that you have git installed on platforms where it knows how to get a binary. If you already have git on your system path it'll just use it.

Prepare for upcoming deletion of Base.Git module

---

src/Coverage.jl

`isdefined(a, 5)` is deprecated in 0.6-dev, and changing it to `isassigned` works even on julia-0.4. Needed to avoid insanely-long travis builds (https://travis-ci.org/JuliaLang/DataStructures.jl/builds/158928733).

isdefined->isassigned

---

README.md
src/codecovio.jl
src/coveralls.jl
test/runtests.jl

These changes let you push coverage reports to CodeCov from AppVeyor builds. However, for now this will only be useful for Julia versions <= 0.4 (see [here](https://github.com/JuliaLang/julia/issues/21289)).
Closes #124

Submit coverage reports from AppVeyor

---

README.md

Examples in README were wrong as the Windows command line doesn't like single quotes.

Fix quotations used in Appveyor example

---

test/runtests.jl

This line fails since it is not properly escaped  in windows where the  path delimiter is `\`

fix include bug, escape_string test filename

---

.travis.yml
REQUIRE
src/memalloc.jl
test/runtests.jl

This is weird to explain so here's an example:
```
[ ~ ] cat > x.jl
using Coverage
print(ARGS)
[ ~ ] julia x.jl fjsf
ERROR: LoadError: LoadError: LoadError: SystemError: opening file fjsf: No such file or directory
Stacktrace:
[1] #systemerror#37 at ./error.jl:64 [inlined]
[2] systemerror(::String, ::Bool) at ./error.jl:64
[3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./iostream.jl:104
[4] open(::Coverage.##17#18{Array{Coverage.MallocInfo,1}}, ::String) at ./iostream.jl:150
[5] analyze_malloc_files(::Array{String,1}) at /Users/degraafc/.julia/v0.6/Coverage/src/memalloc.jl:20
[6] include_from_node1(::String) at ./loading.jl:539
[7] include(::String) at ./sysimg.jl:14
[8] include_from_node1(::String) at ./loading.jl:539
while loading …
```

Let programs using Coverage use command-line arguments

---

src/codecovio.jl
test/runtests.jl

It's the third CI platform supported by/supporting CodeCov by default so I think it's reasonable to support it in Coverage.jl.
I didn't include the `job` key (there's no unique job number in Circle CI) but I did include the `build_url` key.

Add support for Circle CI

---

src/codecovio.jl

Apparently this variable is unset on non-PR builds. Travis sets it to `"false"` in those cases, so that should be fine here.

Fix Circle CI PR number not available on non-PR builds

---

test/runtests.jl

* Parsing seems to have changed slightly in Julia (or JuliaParser?) between v0.6 and v0.7.
For test/data/testparser.jl, line 10 is the end of a @doc string (`""" ->`), and Line 11
is an expression (`f6(x) = 6x`)
* In v0.6, the zero count goes to line 10, and in v0.7, the zero count goes (more correctly?)
to line 11

Fix tests on Julia v0.7

---

test/runtests.jl

The commit that broke the tests here on 0.7 (which was fixed by #136) was backported to 0.6.1. Once that's released, the tests will fail on the latest 0.6 release, so this PR adjusts the test to look for all applicable versions.

Fix tests on 0.6.1

---

.travis.yml

Currently coverage information is submitted in the `after_success` block of the Travis script, as it is in most packages. This makes sense for the vast majority of packages, since if coverage submission fails you don't want it to fail your build. However, that's exactly what we want to happen if submission fails here.
This commit restructures the tests to put the coverage submission in the `script` block. This should cause the build to fail if submission fails.

Restructure Travis tests to be more transparent

---

src/Coverage.jl
test/runtests.jl

Noticed this error on Julia 0.6.3 with Coverage 0.5.3:
```
...
Coverage.process_folder: Skipping utils.jl.565.cov, not a .jl file
ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
[1] _mapreduce(::Coverage.##1#3, ::Base.#+, ::IndexLinear, ::Array{Union{Int64, Void},1}) at ./reduce.jl:265
[2] get_summary(::Coverage.FileCoverage) at /root/.julia/v0.6/Coverage/src/Coverage.jl:51
[3] get_summary(::Array{Coverage.FileCoverage,1}) at /root/.julia/v0.6/Coverage/src/Coverage.jl:58
[4] (::##1#2)() at /usr/local/bin/julia-coverage:25
[5] cd(::##1#2, ::String) at ./file.jl:70
[6] include_from_node1(::String) at ./loading.jl:576
[7] include(::String) at ./sysimg.jl:14
[8] process_options(::Base.JLOptions) at ./client.jl:305
[9] _start() at ./client.jl:371 …
```

Fix error when coverage vector is empty

---

src/parser.jl

The `position` function will always return an `Int64` while the `Meta.parse` only accepts an `Int`. This means that when running 32-bit Julia `Meta.parse` will only accept an `Int32` which causes this call to fail.

Fix Meta.parse call on 32-bit

---

test/REQUIRE
test/runtests.jl

Testsets should provide visibility into exactly which tests are failing on 0.7.
Adding testsets broke the existing `redirect_stdout` code somehow, so I switched to using Suppressor which works and is simpler.

Add testsets and use Suppressor for capturing stdout

---

src/codecovio.jl
src/coveralls.jl
test/runtests.jl

This should fix the test failures reported by JuliaCIBot on https://github.com/JuliaLang/METADATA.jl/pull/19092
Also use `LibGit2.GitRepoExt` instead of `LibGit2.GitRepo` to (try to) load git repository. This should fix #159 and render #160 obsolete.

Skip Codecov.submit_local test if not in a git repo; Use LibGit2.GitRepoExt to (try to) load git repository

---

test/runtests.jl

Should fix JuliaCIBot errors.
For reference, because a level of indentation was added, which makes the diff noisy: https://github.com/JuliaCI/Coverage.jl/pull/186/files?w=1

Properly skip local submission tests if not in a clone

---

src/memalloc.jl

Ready for https://github.com/JuliaLang/julia/pull/29969

support local process malloc

---

test/runtests.jl

The default config for git on Windows is to use `\r\n` line endings, and that breaks the tests. This patch should fix that.

Make sure tests are robust with respect to Win line endings

---

src/Coverage.jl
src/codecovio.jl
src/coveralls.jl
src/lcov.jl
test/runtests.jl

I hope you are oke with basically redoing https://github.com/JuliaCI/Coverage.jl/pull/156? Not sure Manifest changes should be in here, they were added when adding Logging.
Effectively also closes https://github.com/JuliaCI/Coverage.jl/issues/92.

Use logging framework for STDOUT calls

---

Project.toml
src/codecovio.jl
test/runtests.jl

Removes the need for Suppressor, and better shows what is actually tested with the dry run, namely generating the token. When changing this code, I also realized that `submit_generic()`, although exported, is probably not used outside the package? I.e., for CI one would use `submit()`, and for local `submit_local()`. Should that export be removed?

Factored out create_uri_string_* methods for easier testing

---

src/coveralls.jl

In PR #196, part of the changes in PR #197 were reverted, I think by accident (or rather, due to my fault, when rebasing the former I was unaware of the changes in PR #197 which had already been merged some time ago).
This PR restores this. However, I am not 100% sure this is even right; there was a reason we added those http headers. I am assuming the point behind PR #197 was that this is not necessary anymore -- but neither the description of that PR, nor the commits in it, actually explain this (only says this is meant to "fix compatibility with HTTP 0.8 -- but curiously, merging PR #196 did not seem to break any tests?).
So before merging this, I'd like to verify that the cause for the addition of those explicit headers is indeed gone now (discussion of that is on PR #175). I am …

Restore HTTP.post invocation

---

src/parser.jl

Fixes #199.
There are certain function signatures that have a line node in their AST, and then the function signature gets marked as uncovered. That is not good, because there is then no way to actually cover that line. So this just skips the function signature part, and only looks at the body of functions when it comes to amend the line info reported from base.

Only add lines from function bodies for coverage

---

README.md

AppVeyor has changed their permissions model such that builds can run per organization rather than having to be under a specific user's account. I've authorized the AppVeyor integration for the JuliaCI
organization and set up builds for this repo after disabling it running under my account. This simply changes the badge URL to point to the new location.
cc @fingolfin

Update AppVeyor badge to point to JuliaCI

---

README.md
src/Coverage.jl

If the environment variable DISABLE_AMEND_COVERAGE_FROM_SRC is set to `yes`, do not call `amend_coverage_from_src!`. This is an optional mitigation for issue #187, and in general makes it easier to test the impact of amending the coverage data.

Check DISABLE_AMEND_COVERAGE_FROM_SRC env var

---

src/Coverage.jl
src/parser.jl

Improve coverage heuristic in function_body_lines
The purpose of function_body_lines is to find functions which are "dead" (= never executed by test suite), and mark them as code, because Julia's built-in coverage code does not do that; if we were to rely on it, such functions would be marked as non-code, and thus they do not show up in the overall code coverage percentage.
But our current heuristic is too aggressive in so far as that Julia also sometimes marks code lines as "is not code" in the middle of functions that are being executed (most likely due to inlining and other optimizations). If we mark those lines as code, they will show up as uncovered, with no way for the package author to change this.
With this commit, we refine our heuristic: we only apply it to functions for which …

Improve coverage heuristic in function_body_lines

---

src/parser.jl
test/runtests.jl

Motivated by parts of PR #214.
A real life example of dead code not found because of this can be seen [here in the JuliaSpace/ReferenceFrameRotations.jl project](https://codecov.io/gh/JuliaSpace/ReferenceFrameRotations.jl/src/master/src/quaternion.jl#L77) (CC @ronisbr). Just in case the line numbers change, the function in question is this
```julia
Quaternion{T}(u::UniformScaling) where T = Quaternion{T}(T(u.λ), T(0), T(0), T(0))
```

Handle more types of function declarations

---

src/Coverage.jl
src/coveralls.jl
test/runtests.jl

- add some spaces after commas
- use !== instead of != to compare against nothing
- simplify a test by adding empty test/fakefile to repository
- use repr in a test instead of (ab)using escape_string
- use searchsortedfirst(...) instead of minimum(searchsorted(...)0
- rename linestart to lineoffset
- subtract 1 from lineoffset at definition, simplifies (?) following code
- test effect of DISABLE_AMEND_COVERAGE_FROM_SRC
- make tests work if DISABLE_AMEND_COVERAGE_FROM_SRC=yes is set
- fix a typo in a comment
- make a get_summary test more precise
This extracts a bunch of changes from PR #214 that IMHO don't belong in there, logically. We can merge this here quickly, I think, and then rebase PR #214 (I verified that rebasing that is mostly straight forwards, and can also update that PR if …

Miscellaneous cleanup

---

src/Coverage.jl

Our code converting positions into line numbers only produced correct
results at the start of a line. Right now, Meta.parse always returns
such positions, so nothing really was broken; but if this ever changes,
or if we get inputs from another source, we must properly deal with it.
Motivated by a similar fix due to @vtjnash in PR #214

Fix a potential bug in amend_coverage_from_src!

---

src/Coverage.jl
test/runtests.jl

We want to turn on usage of this function for CoverageBase, but currently it assumes that the file must exist (even though we already have the contents in memory). Move a bit of code around to use the fact that we already have the source in memory.

permit flexible use of amend_coverage_from_src!

---

src/parser.jl

avoid potential out-of-bounds array access attempt in `function_body_lines`

add missing bounds check in amend_coverage_from_src

---

src/codecovio.jl
test/runtests.jl

Reimplements #113 .
I have taken a different approach to the original PR: instead of splitting the url construction logic I left that as-is, and used a regex on the full string instead. That makes testing a bit easier as well.
One potential problem might be the line
```
@info "Result of submission:" * String(req)
```
Does this print the url string as well?

Mask codecov token in logs

---

src/Coverage.jl
src/codecovio.jl
src/coveralls.jl
src/lcov.jl

There is no point in Coverage.LCOV.readfolder and Coverage.clean_folder
reporting every file they did *not* process; this just clogs up build logs,
and almost always is useless; so change this from @info to @debug.
Also, by default user won't want to know the JSON replies of Codecov and
Coveralls, nor the exact URL we used to submit to Codecov, so change those
from @info to @debug as well.
On the other hand, knowing which files actually are being processed *is*
useful, so add an @info message for that (I recently had an exception thrown
in that code and had a hard time figuring out which file was being proceed, so
this will help).
Finally, get rid of the `verbose` keyword flag; instead, users can adjust the
logging level to suppress or show various messages.

Remove verbose flag, change some @info to @debug

---

src/codecovio.jl
src/coveralls.jl

Add support for GitHub Actions

---

REQUIRE

Now that there is a `Project.toml` file, we can delete the `REQUIRE` file.

Delete REQUIRE file

---

src/coveralls.jl
test/runtests.jl

We send it to CodeCov.io, so just copying it over to Coveralls.

Add pull request number to Coveralls.io

---

.travis.yml
README.md
src/codecovio.jl
src/coveralls.jl
test/runtests.jl

Fixes #273
Fixes https://github.com/JuliaLang/julia/issues/38173

updates for v1.5, etc.

---

src/codecovio.jl

Addresses issue https://github.com/JuliaCI/Coverage.jl/issues/284

Support Github Actions with Codecov

---

src/memalloc.jl

This is not how packages in Julia are used, especially since precompile. If we wanted something like this back, it would be more logical to have a simple script `bin/memalloc` to drive this functionality.
Closes #98

memalloc: remove dead code

---

src/codecovio.jl
src/coveralls.jl

remove deprecations and depwarns

---

src/codecovio.jl

Previously, this would print an html page, now it will print the error message
Fixes #276

Coveralls: fix error reporting printing

---

src/codecovio.jl
src/coveralls.jl

Based on the [official docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables).

Expand on data extraction from github action runs for Coveralls

---

Project.toml
etc/travis-coverage.jl
src/coveralls.jl

Fixes #314 
Closes #310 
Closes #313

Fix Coveralls submission, and re-enable Coveralls submission from CI

---

.github/workflows/CI.yml
Project.toml
src/codecovio.jl
test/runtests.jl

Closes #304 
Here is this diff for this PR versus PR #304: https://github.com/JuliaCI/Coverage.jl/compare/aa/codecov-v4...dpa/codecov-v4

Update Codecov upload API to v4 (replacement for #304)

---

Project.toml
src/Coverage.jl
src/codecovio.jl
src/coveralls.jl

Most Julia packages follow the convention that you don't increase an indentation level inside a `module`.
This PR fixes the code in this package to follow that convention.
There are no changes other than fixing the indentation and whitespace.

Fix indentation inside `module`s

---

Project.toml
src/coveralls.jl

Coveralls: fix a deprecated HTTP post call

---

src/codecovio.jl
test/runtests.jl

Only added to Codecov, since as Coveralls [doesn't seem to support](https://docs.coveralls.io/supported-ci-services) Buildkite. Not that [Codecov supports tokenless uploads](https://community.codecov.com/t/buildkite-token-less-upload/2259) from Buildkite, but this at least avoids the need for local git operations to populate the branch, commit, etc.

Add support for Buildkite.

---

Project.toml
src/codecovio.jl
src/coveralls.jl
test/runtests.jl

This allows to directly submit the Coverage report to Codecov or Coveralls from a Gitlab action.
This solves #330

Add Gitlab CI to Coverage

---

README.md

Fix https://github.com/JuliaCI/Coverage.jl/issues/326.
@IainNZ, @fingolfin or @kshyatt, bump ?

document  `COV_EXCL_START`, `COV_EXCL_STOP` and `COV_EXCL_LINE`

---

README.md

it seems the path to Julia has changed in Appveyor, to ```C:\julia\bin\julia```, so the readme should be adapted accordingly.
Closes #339
Closes #328

Path to julia Appveyor
